import type { Request, Response } from "express";
import PDFDocument from "pdfkit";
import { prisma } from "../lib/prisma.js";
import type { AuthenticatedRequest } from "../middleware/authenticate.js";

const money = (value: unknown) =>
  `$${Number(value ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2 })}`;

const date = (value: Date) =>
  new Date(value).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

// GET /api/leases/:leaseId/agreement — the signed lease terms as a PDF.
// Visible to the tenant on the lease and to the manager of its property.
export async function getLeaseAgreement(req: Request, res: Response) {
  try {
    const user = (req as AuthenticatedRequest).user;
    const leaseId = Array.isArray(req.params.leaseId)
      ? req.params.leaseId[0]
      : req.params.leaseId;

    const lease = await prisma.lease.findUnique({
      where: { id: leaseId },
      include: {
        property: {
          include: {
            manager: { include: { user: { select: { name: true, email: true } } } },
          },
        },
        tenant: { include: { user: { select: { name: true, email: true } } } },
        payments: { orderBy: { dueDate: "asc" } },
      },
    });
    if (!lease)
      return res.status(404).json({ error: "Lease not found" });

    const isTenant = lease.tenant.userId === user.id;
    const isManager = lease.property.manager.userId === user.id;
    if (!isTenant && !isManager)
      return res.status(403).json({ error: "Forbidden: You are not a party to this lease" });

    const filename = `Lease_Agreement_${lease.property.name.replace(/\s+/g, "_")}.pdf`;
    res.setHeader("Content-Type", "application/pdf");
    // ?inline=1 renders in a browser tab (View Lease); default downloads.
    res.setHeader(
      "Content-Disposition",
      `${req.query.inline === "1" ? "inline" : "attachment"}; filename="${filename}"`,
    );

    const doc = new PDFDocument({ margin: 56 });
    doc.pipe(res);

    doc.fontSize(20).text("Residential Lease Agreement", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("gray").text(
      `${lease.property.name} — ${lease.property.address}, ${lease.property.city}, ${lease.property.state} ${lease.property.postalCode}`,
      { align: "center" },
    );
    doc.fillColor("black").moveDown();

    const row = (label: string, value: string) => {
      doc.fontSize(11).font("Helvetica-Bold").text(label, { continued: true });
      doc.font("Helvetica").text(`  ${value}`);
      doc.moveDown(0.25);
    };

    doc.fontSize(13).text("Parties");
    row("Tenant:", `${lease.tenant.user.name} (${lease.tenant.user.email})`);
    row("Manager:", `${lease.property.manager.user.name} (${lease.property.manager.user.email})`);
    doc.moveDown(0.5);

    doc.fontSize(13).text("Term & Rent");
    row("Property:", `${lease.property.name}, ${lease.property.address}, ${lease.property.city}`);
    row("Lease term:", `${date(lease.startDate)} — ${date(lease.endDate)}`);
    row("Monthly rent:", money(lease.rent));
    row("Security deposit:", money(lease.deposit));
    doc.moveDown(0.5);

    doc.fontSize(13).text("Payment Schedule");
    if (lease.payments.length === 0) {
      doc.fontSize(11).text("No invoices have been issued against this lease yet.");
    } else {
      for (const p of lease.payments) {
        row(
          date(p.dueDate),
          `${money(p.amountDue)} due — ${money(p.amountPaid)} paid (${p.paymentStatus})`,
        );
      }
    }
    doc.moveDown();

    doc.fontSize(9).fillColor("gray").text(
      `Generated by Habitat on ${date(new Date())}. Lease ref ${lease.id}. ` +
        "This document summarizes the lease record; the signed original, where one exists, prevails.",
    );

    doc.end();
  } catch (error) {
    console.error("Error generating lease agreement:", error);
    if (!res.headersSent)
      return res.status(500).json({ error: "Failed to generate lease agreement" });
  }
}

// GET /api/leases/payments/:paymentId/receipt — single-invoice receipt.
// Same party rule as the agreement: the tenant on the lease or its
// property's manager.
export async function getPaymentReceipt(req: Request, res: Response) {
  try {
    const user = (req as AuthenticatedRequest).user;
    const paymentId = Array.isArray(req.params.paymentId)
      ? req.params.paymentId[0]
      : req.params.paymentId;

    const payment = await prisma.payment.findUnique({
      where: { id: paymentId },
      include: {
        lease: {
          include: {
            property: true,
            tenant: { include: { user: { select: { name: true, email: true } } } },
          },
        },
      },
    });
    if (!payment)
      return res.status(404).json({ error: "Invoice not found" });

    const tenant = await prisma.tenant.findUnique({
      where: { id: payment.lease.tenantId },
      select: { userId: true },
    });
    const manager = await prisma.manager.findUnique({
      where: { id: payment.lease.property.managerId },
      select: { userId: true },
    });
    if (user.id !== tenant?.userId && user.id !== manager?.userId)
      return res.status(403).json({ error: "Forbidden: You are not a party to this lease" });

    const filename = `Receipt_${payment.id.slice(0, 8).toUpperCase()}.pdf`;
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);

    const doc = new PDFDocument({ margin: 56 });
    doc.pipe(res);

    doc.fontSize(20).text("Payment Receipt", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("gray").text(
      `${payment.lease.property.name} — ${payment.lease.property.address}, ${payment.lease.property.city}`,
      { align: "center" },
    );
    doc.fillColor("black").moveDown();

    const row = (label: string, value: string) => {
      doc.fontSize(11).font("Helvetica-Bold").text(label, { continued: true });
      doc.font("Helvetica").text(`  ${value}`);
      doc.moveDown(0.25);
    };

    row("Receipt:", filename.replace(".pdf", ""));
    row("Tenant:", `${payment.lease.tenant.user.name} (${payment.lease.tenant.user.email})`);
    row("Lease term:", `${date(payment.lease.startDate)} — ${date(payment.lease.endDate)}`);
    row("Due date:", date(payment.dueDate));
    row("Amount due:", money(payment.amountDue));
    row("Amount paid:", money(payment.amountPaid));
    row("Balance:", money(Number(payment.amountDue) - Number(payment.amountPaid)));
    row("Status:", payment.paymentStatus);
    if (payment.paymentDate) row("Paid on:", date(payment.paymentDate));
    doc.moveDown();

    doc.fontSize(9).fillColor("gray").text(
      `Generated by Habitat on ${date(new Date())}. Record ref ${payment.id}.`,
    );

    doc.end();
  } catch (error) {
    console.error("Error generating payment receipt:", error);
    if (!res.headersSent)
      return res.status(500).json({ error: "Failed to generate receipt" });
  }
}
