import type { Request, Response } from "express";
import { prisma } from "../lib/prisma.js";
import type { AuthenticatedRequest } from "../middleware/authenticate.js";
import { getOrCreateTenant } from "../middleware/authorize.js";

const leaseWithProperty = {
  property: true,
};

// A tenant's current residence is whichever lease's date range includes
// today. Only one lease is treated as active at a time (enforced when a
// lease is created on application approval).
export async function getCurrentLease(req: Request, res: Response) {
  try {
    const user = (req as AuthenticatedRequest).user;
    const tenant = await getOrCreateTenant(user.id);
    const now = new Date();

    const currentLease = await prisma.lease.findFirst({
      where: {
        tenantId: tenant.id,
        startDate: { lte: now },
        endDate: { gte: now },
      },
      orderBy: { startDate: "desc" },
      include: leaseWithProperty,
    });

    const pastLeases = await prisma.lease.findMany({
      where: {
        tenantId: tenant.id,
        endDate: { lt: now },
      },
      orderBy: { endDate: "desc" },
      include: leaseWithProperty,
    });

    return res.json({ currentLease, pastLeases });
  } catch (error) {
    console.error("Error fetching current lease:", error);
    return res.status(500).json({ error: "Failed to fetch current lease" });
  }
}

// GET /api/tenant/payments/statement — full payment-history statement
// as a PDF. Optional ?from=YYYY-MM-DD&to=YYYY-MM-DD filters by due date.
export async function getPaymentStatement(req: Request, res: Response) {
  try {
    const user = (req as AuthenticatedRequest).user;
    const tenant = await getOrCreateTenant(user.id);

    const { from, to } = req.query;
    const dueFilter: Record<string, Date> = {};
    if (typeof from === "string" && !Number.isNaN(Date.parse(from)))
      dueFilter.gte = new Date(from);
    if (typeof to === "string" && !Number.isNaN(Date.parse(to)))
      dueFilter.lte = new Date(`${to}T23:59:59`);

    const payments = await prisma.payment.findMany({
      where: {
        lease: { tenantId: tenant.id },
        ...(Object.keys(dueFilter).length > 0 ? { dueDate: dueFilter } : {}),
      },
      orderBy: { dueDate: "asc" },
      include: {
        lease: {
          select: {
            property: { select: { name: true, address: true } },
          },
        },
      },
    });

    const { default: PDFDocument } = await import("pdfkit");
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", 'attachment; filename="Payment_Statement.pdf"');

    const doc = new PDFDocument({ margin: 56 });
    doc.pipe(res);

    const money = (v: unknown) =>
      `$${Number(v ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2 })}`;
    const date = (v: Date) =>
      new Date(v).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });

    doc.fontSize(20).text("Payment Statement", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("gray").text(
      `${user.name} (${user.email})` +
        (typeof from === "string" || typeof to === "string"
          ? ` — due ${(from as string) || "…"} to ${(to as string) || "…"}` : ""),
      { align: "center" },
    );
    doc.fillColor("black").moveDown();

    let totalDue = 0;
    let totalPaid = 0;
    for (const p of payments) {
      totalDue += Number(p.amountDue);
      totalPaid += Number(p.amountPaid);
      doc.fontSize(11).font("Helvetica-Bold")
        .text(date(p.dueDate), { continued: true });
      doc.font("Helvetica").text(
        `  ${p.lease.property.name} — ${money(p.amountDue)} due, ${money(p.amountPaid)} paid (${p.paymentStatus})`,
      );
      doc.moveDown(0.25);
    }
    doc.moveDown(0.5);
    doc.fontSize(12).font("Helvetica-Bold")
      .text(`Totals  ${money(totalDue)} due  •  ${money(totalPaid)} paid  •  ${money(totalDue - totalPaid)} outstanding`);
    doc.moveDown();
    doc.fontSize(9).fillColor("gray").text(
      `Generated by Habitat on ${date(new Date())}. ${payments.length} invoices.`,
    );

    doc.end();
  } catch (error) {
    console.error("Error generating payment statement:", error);
    if (!res.headersSent)
      return res.status(500).json({ error: "Failed to generate statement" });
  }
}

// PATCH /api/tenant/payments/:paymentId/pay — pay down one of your own
// invoices. Body { amount? } defaults to the full remaining balance.
// Partial payments accumulate on amountPaid and flip status Paid only
// once amountPaid covers amountDue.
export async function payInvoice(req: Request, res: Response) {
  try {
    const user = (req as AuthenticatedRequest).user;
    const tenant = await getOrCreateTenant(user.id);
    const paymentId = Array.isArray(req.params.paymentId)
      ? req.params.paymentId[0]
      : req.params.paymentId;

    const payment = await prisma.payment.findUnique({
      where: { id: paymentId },
      include: { lease: { select: { tenantId: true } } },
    });
    if (!payment || payment.lease.tenantId !== tenant.id)
      return res.status(404).json({ error: "Invoice not found" });

    const due = Number(payment.amountDue);
    const paid = Number(payment.amountPaid);
    const balance = due - paid;
    if (balance <= 0)
      return res.status(409).json({ error: "This invoice is already paid" });

    const { amount } = req.body;
    const payAmount = amount === undefined ? balance : Number(amount);
    if (!Number.isFinite(payAmount) || payAmount <= 0)
      return res.status(400).json({ error: "Amount must be a positive number" });
    if (payAmount - balance > 0.005)
      return res.status(400).json({ error: `Amount exceeds the ${balance.toFixed(2)} balance` });

    const newPaid = paid + payAmount;
    const updated = await prisma.payment.update({
      where: { id: paymentId },
      data: {
        amountPaid: newPaid,
        paymentDate: new Date(),
        paymentStatus: newPaid - due >= -0.005 ? "Paid" : "PartiallyPaid",
      },
    });

    return res.json({ payment: updated });
  } catch (error) {
    console.error("Error paying invoice:", error);
    return res.status(500).json({ error: "Failed to record payment" });
  }
}
export async function getTenantPayments(req: Request, res: Response) {
  try {
    const user = (req as AuthenticatedRequest).user;
    const tenant = await getOrCreateTenant(user.id);

    const payments = await prisma.payment.findMany({
      where: { lease: { tenantId: tenant.id } },
      orderBy: { dueDate: "desc" },
      include: {
        lease: {
          select: {
            id: true,
            startDate: true,
            endDate: true,
            property: {
              select: { id: true, name: true, address: true },
            },
          },
        },
      },
    });

    return res.json({ payments });
  } catch (error) {
    console.error("Error fetching tenant payments:", error);
    return res.status(500).json({ error: "Failed to fetch payments" });
  }
}
